void ETauFR_failLt2p300VLoose_prefit()
{
//=========Macro generated from canvas: canv1/
//=========  (Wed May 12 12:13:27 2021) by ROOT version 6.14/09
   TCanvas *canv1 = new TCanvas("canv1", "",0,23,1000,755);
   canv1->Range(0,0,1,1);
   canv1->SetFillColor(0);
   canv1->SetBorderMode(0);
   canv1->SetBorderSize(2);
   canv1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: upper
   TPad *upper = new TPad("upper", "pad",0,0.31,1,1);
   upper->Draw();
   upper->cd();
   upper->Range(46.92308,-2566.259,123.8462,125746.7);
   upper->SetFillColor(0);
   upper->SetBorderMode(0);
   upper->SetBorderSize(10);
   upper->SetTickx(1);
   upper->SetTicky(1);
   upper->SetLeftMargin(0.17);
   upper->SetRightMargin(0.05);
   upper->SetBottomMargin(0.02);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   upper->SetFrameFillStyle(0);
   upper->SetFrameLineStyle(0);
   upper->SetFrameLineWidth(2);
   upper->SetFrameBorderMode(0);
   upper->SetFrameBorderSize(10);
   
   TH1F *data_obs__1 = new TH1F("data_obs__1","",1,60,120);
   data_obs__1->SetBinContent(1,86858);
   data_obs__1->SetBinError(1,294.7168);
   data_obs__1->SetMinimum(0);
   data_obs__1->SetMaximum(112915.4);
   data_obs__1->SetEntries(1);
   data_obs__1->SetStats(0);
   data_obs__1->SetOption("E1");
   data_obs__1->SetFillStyle(0);
   data_obs__1->SetLineWidth(2);
   data_obs__1->SetMarkerStyle(20);
   data_obs__1->SetMarkerSize(1.5);
   data_obs__1->GetXaxis()->SetTitle("m_{vis} [GeV]");
   data_obs__1->GetXaxis()->SetRange(1,1);
   data_obs__1->GetXaxis()->SetLabelFont(42);
   data_obs__1->GetXaxis()->SetLabelOffset(0.007);
   data_obs__1->GetXaxis()->SetLabelSize(0);
   data_obs__1->GetXaxis()->SetTitleSize(0.06);
   data_obs__1->GetXaxis()->SetTitleOffset(0.9);
   data_obs__1->GetXaxis()->SetTitleFont(42);
   data_obs__1->GetYaxis()->SetTitle("dN/dm_{vis}[1/GeV]");
   data_obs__1->GetYaxis()->SetLabelFont(42);
   data_obs__1->GetYaxis()->SetLabelOffset(0.007);
   data_obs__1->GetYaxis()->SetLabelSize(0.06);
   data_obs__1->GetYaxis()->SetTitleSize(0.06);
   data_obs__1->GetYaxis()->SetTitleOffset(1.5);
   data_obs__1->GetYaxis()->SetTitleFont(42);
   data_obs__1->GetZaxis()->SetLabelFont(42);
   data_obs__1->GetZaxis()->SetLabelOffset(0.007);
   data_obs__1->GetZaxis()->SetLabelSize(0.05);
   data_obs__1->GetZaxis()->SetTitleSize(0.06);
   data_obs__1->GetZaxis()->SetTitleFont(42);
   data_obs__1->Draw("e1");
   
   TH1F *ZL__2 = new TH1F("ZL__2","Observed",1,60,120);
   ZL__2->SetBinContent(1,71520.2);
   ZL__2->SetEntries(7);
   ZL__2->SetStats(0);
   ZL__2->SetOption("E1");

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#de5a6a");
   ZL__2->SetFillColor(ci);
   ZL__2->SetLineWidth(2);
   ZL__2->SetMarkerStyle(21);
   ZL__2->SetMarkerSize(0);
   ZL__2->GetXaxis()->SetTitle("m_{vis} [GeV]");
   ZL__2->GetXaxis()->SetLabelFont(42);
   ZL__2->GetXaxis()->SetLabelOffset(0.007);
   ZL__2->GetXaxis()->SetLabelSize(0.05);
   ZL__2->GetXaxis()->SetTitleSize(0.06);
   ZL__2->GetXaxis()->SetTitleOffset(0.9);
   ZL__2->GetXaxis()->SetTitleFont(42);
   ZL__2->GetYaxis()->SetLabelFont(42);
   ZL__2->GetYaxis()->SetLabelOffset(0.007);
   ZL__2->GetYaxis()->SetLabelSize(0.05);
   ZL__2->GetYaxis()->SetTitleSize(0.06);
   ZL__2->GetYaxis()->SetTitleOffset(1.25);
   ZL__2->GetYaxis()->SetTitleFont(42);
   ZL__2->GetZaxis()->SetLabelFont(42);
   ZL__2->GetZaxis()->SetLabelOffset(0.007);
   ZL__2->GetZaxis()->SetLabelSize(0.05);
   ZL__2->GetZaxis()->SetTitleSize(0.06);
   ZL__2->GetZaxis()->SetTitleFont(42);
   ZL__2->Draw("sameh");
   
   TH1F *ZJ__3 = new TH1F("ZJ__3","Observed",1,60,120);
   ZJ__3->SetBinContent(1,2117.401);
   ZJ__3->SetEntries(6);
   ZJ__3->SetStats(0);
   ZJ__3->SetOption("E1");

   ci = TColor::GetColor("#ffcc66");
   ZJ__3->SetFillColor(ci);
   ZJ__3->SetLineWidth(2);
   ZJ__3->SetMarkerStyle(21);
   ZJ__3->SetMarkerSize(0);
   ZJ__3->GetXaxis()->SetTitle("m_{vis} [GeV]");
   ZJ__3->GetXaxis()->SetLabelFont(42);
   ZJ__3->GetXaxis()->SetLabelOffset(0.007);
   ZJ__3->GetXaxis()->SetLabelSize(0.05);
   ZJ__3->GetXaxis()->SetTitleSize(0.06);
   ZJ__3->GetXaxis()->SetTitleOffset(0.9);
   ZJ__3->GetXaxis()->SetTitleFont(42);
   ZJ__3->GetYaxis()->SetLabelFont(42);
   ZJ__3->GetYaxis()->SetLabelOffset(0.007);
   ZJ__3->GetYaxis()->SetLabelSize(0.05);
   ZJ__3->GetYaxis()->SetTitleSize(0.06);
   ZJ__3->GetYaxis()->SetTitleOffset(1.25);
   ZJ__3->GetYaxis()->SetTitleFont(42);
   ZJ__3->GetZaxis()->SetLabelFont(42);
   ZJ__3->GetZaxis()->SetLabelOffset(0.007);
   ZJ__3->GetZaxis()->SetLabelSize(0.05);
   ZJ__3->GetZaxis()->SetTitleSize(0.06);
   ZJ__3->GetZaxis()->SetTitleFont(42);
   ZJ__3->Draw("sameh");
   
   TH1F *VV__4 = new TH1F("VV__4","Observed",1,60,120);
   VV__4->SetBinContent(1,1386.534);
   VV__4->SetEntries(4);
   VV__4->SetStats(0);
   VV__4->SetOption("E1");

   ci = TColor::GetColor("#6f2d35");
   VV__4->SetFillColor(ci);
   VV__4->SetLineWidth(2);
   VV__4->SetMarkerStyle(21);
   VV__4->SetMarkerSize(0);
   VV__4->GetXaxis()->SetTitle("m_{vis} [GeV]");
   VV__4->GetXaxis()->SetLabelFont(42);
   VV__4->GetXaxis()->SetLabelOffset(0.007);
   VV__4->GetXaxis()->SetLabelSize(0.05);
   VV__4->GetXaxis()->SetTitleSize(0.06);
   VV__4->GetXaxis()->SetTitleOffset(0.9);
   VV__4->GetXaxis()->SetTitleFont(42);
   VV__4->GetYaxis()->SetLabelFont(42);
   VV__4->GetYaxis()->SetLabelOffset(0.007);
   VV__4->GetYaxis()->SetLabelSize(0.05);
   VV__4->GetYaxis()->SetTitleSize(0.06);
   VV__4->GetYaxis()->SetTitleOffset(1.25);
   VV__4->GetYaxis()->SetTitleFont(42);
   VV__4->GetZaxis()->SetLabelFont(42);
   VV__4->GetZaxis()->SetLabelOffset(0.007);
   VV__4->GetZaxis()->SetLabelSize(0.05);
   VV__4->GetZaxis()->SetTitleSize(0.06);
   VV__4->GetZaxis()->SetTitleFont(42);
   VV__4->Draw("sameh");
   
   TH1F *TTT__5 = new TH1F("TTT__5","Observed",1,60,120);
   TTT__5->SetBinContent(1,1333.234);
   TTT__5->SetEntries(3);
   TTT__5->SetStats(0);
   TTT__5->SetOption("E1");

   ci = TColor::GetColor("#9999cc");
   TTT__5->SetFillColor(ci);
   TTT__5->SetLineWidth(2);
   TTT__5->SetMarkerStyle(21);
   TTT__5->SetMarkerSize(0);
   TTT__5->GetXaxis()->SetTitle("m_{vis} [GeV]");
   TTT__5->GetXaxis()->SetLabelFont(42);
   TTT__5->GetXaxis()->SetLabelOffset(0.007);
   TTT__5->GetXaxis()->SetLabelSize(0.05);
   TTT__5->GetXaxis()->SetTitleSize(0.06);
   TTT__5->GetXaxis()->SetTitleOffset(0.9);
   TTT__5->GetXaxis()->SetTitleFont(42);
   TTT__5->GetYaxis()->SetLabelFont(42);
   TTT__5->GetYaxis()->SetLabelOffset(0.007);
   TTT__5->GetYaxis()->SetLabelSize(0.05);
   TTT__5->GetYaxis()->SetTitleSize(0.06);
   TTT__5->GetYaxis()->SetTitleOffset(1.25);
   TTT__5->GetYaxis()->SetTitleFont(42);
   TTT__5->GetZaxis()->SetLabelFont(42);
   TTT__5->GetZaxis()->SetLabelOffset(0.007);
   TTT__5->GetZaxis()->SetLabelSize(0.05);
   TTT__5->GetZaxis()->SetTitleSize(0.06);
   TTT__5->GetZaxis()->SetTitleFont(42);
   TTT__5->Draw("sameh");
   
   TH1F *W__6 = new TH1F("W__6","Observed",1,60,120);
   W__6->SetBinContent(1,1326.165);
   W__6->SetEntries(2);
   W__6->SetStats(0);
   W__6->SetOption("E1");

   ci = TColor::GetColor("#4496c8");
   W__6->SetFillColor(ci);
   W__6->SetLineWidth(2);
   W__6->SetMarkerStyle(21);
   W__6->SetMarkerSize(0);
   W__6->GetXaxis()->SetTitle("m_{vis} [GeV]");
   W__6->GetXaxis()->SetLabelFont(42);
   W__6->GetXaxis()->SetLabelOffset(0.007);
   W__6->GetXaxis()->SetLabelSize(0.05);
   W__6->GetXaxis()->SetTitleSize(0.06);
   W__6->GetXaxis()->SetTitleOffset(0.9);
   W__6->GetXaxis()->SetTitleFont(42);
   W__6->GetYaxis()->SetLabelFont(42);
   W__6->GetYaxis()->SetLabelOffset(0.007);
   W__6->GetYaxis()->SetLabelSize(0.05);
   W__6->GetYaxis()->SetTitleSize(0.06);
   W__6->GetYaxis()->SetTitleOffset(1.25);
   W__6->GetYaxis()->SetTitleFont(42);
   W__6->GetZaxis()->SetLabelFont(42);
   W__6->GetZaxis()->SetLabelOffset(0.007);
   W__6->GetZaxis()->SetLabelSize(0.05);
   W__6->GetZaxis()->SetTitleSize(0.06);
   W__6->GetZaxis()->SetTitleFont(42);
   W__6->Draw("sameh");
   
   TH1F *QCD__7 = new TH1F("QCD__7","Observed",1,60,120);
   QCD__7->SetBinContent(1,1267.99);
   QCD__7->SetEntries(1);
   QCD__7->SetStats(0);
   QCD__7->SetOption("E1");

   ci = TColor::GetColor("#ffccff");
   QCD__7->SetFillColor(ci);
   QCD__7->SetLineWidth(2);
   QCD__7->SetMarkerStyle(21);
   QCD__7->SetMarkerSize(0);
   QCD__7->GetXaxis()->SetTitle("m_{vis} [GeV]");
   QCD__7->GetXaxis()->SetLabelFont(42);
   QCD__7->GetXaxis()->SetLabelOffset(0.007);
   QCD__7->GetXaxis()->SetLabelSize(0.05);
   QCD__7->GetXaxis()->SetTitleSize(0.06);
   QCD__7->GetXaxis()->SetTitleOffset(0.9);
   QCD__7->GetXaxis()->SetTitleFont(42);
   QCD__7->GetYaxis()->SetLabelFont(42);
   QCD__7->GetYaxis()->SetLabelOffset(0.007);
   QCD__7->GetYaxis()->SetLabelSize(0.05);
   QCD__7->GetYaxis()->SetTitleSize(0.06);
   QCD__7->GetYaxis()->SetTitleOffset(1.25);
   QCD__7->GetYaxis()->SetTitleFont(42);
   QCD__7->GetZaxis()->SetLabelFont(42);
   QCD__7->GetZaxis()->SetLabelOffset(0.007);
   QCD__7->GetZaxis()->SetLabelSize(0.05);
   QCD__7->GetZaxis()->SetTitleSize(0.06);
   QCD__7->GetZaxis()->SetTitleFont(42);
   QCD__7->Draw("sameh");
   
   TH1F *data_obs__8 = new TH1F("data_obs__8","",1,60,120);
   data_obs__8->SetBinContent(1,86858);
   data_obs__8->SetBinError(1,294.7168);
   data_obs__8->SetMinimum(0);
   data_obs__8->SetMaximum(112915.4);
   data_obs__8->SetEntries(1);
   data_obs__8->SetStats(0);
   data_obs__8->SetOption("E1");
   data_obs__8->SetFillStyle(0);
   data_obs__8->SetLineWidth(2);
   data_obs__8->SetMarkerStyle(20);
   data_obs__8->SetMarkerSize(1.5);
   data_obs__8->GetXaxis()->SetTitle("m_{vis} [GeV]");
   data_obs__8->GetXaxis()->SetRange(1,1);
   data_obs__8->GetXaxis()->SetLabelFont(42);
   data_obs__8->GetXaxis()->SetLabelOffset(0.007);
   data_obs__8->GetXaxis()->SetLabelSize(0);
   data_obs__8->GetXaxis()->SetTitleSize(0.06);
   data_obs__8->GetXaxis()->SetTitleOffset(0.9);
   data_obs__8->GetXaxis()->SetTitleFont(42);
   data_obs__8->GetYaxis()->SetTitle("dN/dm_{vis}[1/GeV]");
   data_obs__8->GetYaxis()->SetLabelFont(42);
   data_obs__8->GetYaxis()->SetLabelOffset(0.007);
   data_obs__8->GetYaxis()->SetLabelSize(0.06);
   data_obs__8->GetYaxis()->SetTitleSize(0.06);
   data_obs__8->GetYaxis()->SetTitleOffset(1.5);
   data_obs__8->GetYaxis()->SetTitleFont(42);
   data_obs__8->GetZaxis()->SetLabelFont(42);
   data_obs__8->GetZaxis()->SetLabelOffset(0.007);
   data_obs__8->GetZaxis()->SetLabelSize(0.05);
   data_obs__8->GetZaxis()->SetTitleSize(0.06);
   data_obs__8->GetZaxis()->SetTitleFont(42);
   data_obs__8->Draw("e1same");
   
   TH1F *bkgdErr__9 = new TH1F("bkgdErr__9","Observed",1,60,120);
   bkgdErr__9->SetBinContent(1,71520.2);
   bkgdErr__9->SetBinError(1,8015.347);
   bkgdErr__9->SetBinError(2,0.05830952);
   bkgdErr__9->SetEntries(7);
   bkgdErr__9->SetOption("E1");
   bkgdErr__9->SetFillColor(1);
   bkgdErr__9->SetFillStyle(3013);
   bkgdErr__9->SetMarkerStyle(21);
   bkgdErr__9->SetMarkerSize(0);
   bkgdErr__9->GetXaxis()->SetTitle("m_{vis} [GeV]");
   bkgdErr__9->GetXaxis()->SetLabelFont(42);
   bkgdErr__9->GetXaxis()->SetLabelOffset(0.007);
   bkgdErr__9->GetXaxis()->SetLabelSize(0.05);
   bkgdErr__9->GetXaxis()->SetTitleSize(0.06);
   bkgdErr__9->GetXaxis()->SetTitleOffset(0.9);
   bkgdErr__9->GetXaxis()->SetTitleFont(42);
   bkgdErr__9->GetYaxis()->SetLabelFont(42);
   bkgdErr__9->GetYaxis()->SetLabelOffset(0.007);
   bkgdErr__9->GetYaxis()->SetLabelSize(0.05);
   bkgdErr__9->GetYaxis()->SetTitleSize(0.06);
   bkgdErr__9->GetYaxis()->SetTitleOffset(1.25);
   bkgdErr__9->GetYaxis()->SetTitleFont(42);
   bkgdErr__9->GetZaxis()->SetLabelFont(42);
   bkgdErr__9->GetZaxis()->SetLabelOffset(0.007);
   bkgdErr__9->GetZaxis()->SetLabelSize(0.05);
   bkgdErr__9->GetZaxis()->SetTitleSize(0.06);
   bkgdErr__9->GetZaxis()->SetTitleFont(42);
   bkgdErr__9->Draw("e2same");
   
   TLegend *leg = new TLegend(0.7,0.6,0.95,0.88,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.05);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("data_obs","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(42);
   entry=leg->AddEntry("VV","Dibosons","f");

   ci = TColor::GetColor("#6f2d35");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("W","WJets","f");

   ci = TColor::GetColor("#4496c8");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("QCD","QCD","f");

   ci = TColor::GetColor("#ffccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TTT","t#bar{t}","f");

   ci = TColor::GetColor("#9999cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("ZJ","DY others","f");

   ci = TColor::GetColor("#ffcc66");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("ZL","Z#rightarrow ee","f");

   ci = TColor::GetColor("#de5a6a");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.65,0.94,"L = 59.9 fb^{-1} at #sqrt{s} = 13 TeV");
tex->SetNDC();
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.85,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.8,"Work in progress");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *data_obs_copy__10 = new TH1F("data_obs_copy__10","",1,60,120);
   data_obs_copy__10->SetBinContent(1,86858);
   data_obs_copy__10->SetBinError(1,294.7168);
   data_obs_copy__10->SetMinimum(0);
   data_obs_copy__10->SetMaximum(112915.4);
   data_obs_copy__10->SetEntries(1);
   data_obs_copy__10->SetDirectory(0);
   data_obs_copy__10->SetStats(0);
   data_obs_copy__10->SetOption("E1");
   data_obs_copy__10->SetFillStyle(0);
   data_obs_copy__10->SetLineWidth(2);
   data_obs_copy__10->SetMarkerStyle(20);
   data_obs_copy__10->SetMarkerSize(1.5);
   data_obs_copy__10->GetXaxis()->SetTitle("m_{vis} [GeV]");
   data_obs_copy__10->GetXaxis()->SetRange(1,1);
   data_obs_copy__10->GetXaxis()->SetLabelFont(42);
   data_obs_copy__10->GetXaxis()->SetLabelOffset(0.007);
   data_obs_copy__10->GetXaxis()->SetLabelSize(0);
   data_obs_copy__10->GetXaxis()->SetTitleSize(0.06);
   data_obs_copy__10->GetXaxis()->SetTitleOffset(0.9);
   data_obs_copy__10->GetXaxis()->SetTitleFont(42);
   data_obs_copy__10->GetYaxis()->SetTitle("dN/dm_{vis}[1/GeV]");
   data_obs_copy__10->GetYaxis()->SetLabelFont(42);
   data_obs_copy__10->GetYaxis()->SetLabelOffset(0.007);
   data_obs_copy__10->GetYaxis()->SetLabelSize(0.06);
   data_obs_copy__10->GetYaxis()->SetTitleSize(0.06);
   data_obs_copy__10->GetYaxis()->SetTitleOffset(1.5);
   data_obs_copy__10->GetYaxis()->SetTitleFont(42);
   data_obs_copy__10->GetZaxis()->SetLabelFont(42);
   data_obs_copy__10->GetZaxis()->SetLabelOffset(0.007);
   data_obs_copy__10->GetZaxis()->SetLabelSize(0.05);
   data_obs_copy__10->GetZaxis()->SetTitleSize(0.06);
   data_obs_copy__10->GetZaxis()->SetTitleFont(42);
   data_obs_copy__10->Draw("sameaxis");
   upper->Modified();
   canv1->cd();
  
// ------------>Primitives in pad: lower
   TPad *lower = new TPad("lower", "pad",0,0,1,0.3);
   lower->Draw();
   lower->cd();
   lower->Range(46.92308,0.2573718,123.8462,1.379167);
   lower->SetFillColor(0);
   lower->SetBorderMode(0);
   lower->SetBorderSize(10);
   lower->SetGridy();
   lower->SetTickx(1);
   lower->SetTicky(1);
   lower->SetLeftMargin(0.17);
   lower->SetRightMargin(0.05);
   lower->SetTopMargin(0.026);
   lower->SetBottomMargin(0.35);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   lower->SetFrameFillStyle(0);
   lower->SetFrameLineStyle(0);
   lower->SetFrameLineWidth(2);
   lower->SetFrameBorderMode(0);
   lower->SetFrameBorderSize(10);
   
   TH1F *ratioH__11 = new TH1F("ratioH__11","",1,60,120);
   ratioH__11->SetBinContent(1,1.214454);
   ratioH__11->SetBinContent(2,1000);
   ratioH__11->SetBinError(1,0.00412075);
   ratioH__11->SetMinimum(0.65);
   ratioH__11->SetMaximum(1.35);
   ratioH__11->SetEntries(13);
   ratioH__11->SetStats(0);
   ratioH__11->SetOption("E1");
   ratioH__11->SetFillStyle(0);
   ratioH__11->SetLineWidth(2);
   ratioH__11->SetMarkerStyle(20);
   ratioH__11->SetMarkerSize(1.5);
   ratioH__11->GetXaxis()->SetTitle("m_{vis} [GeV]");
   ratioH__11->GetXaxis()->SetRange(1,1);
   ratioH__11->GetXaxis()->SetLabelFont(42);
   ratioH__11->GetXaxis()->SetLabelOffset(0.04);
   ratioH__11->GetXaxis()->SetLabelSize(0.14);
   ratioH__11->GetXaxis()->SetTitleSize(0.13);
   ratioH__11->GetXaxis()->SetTickLength(0.07);
   ratioH__11->GetXaxis()->SetTitleOffset(1.2);
   ratioH__11->GetXaxis()->SetTitleFont(42);
   ratioH__11->GetYaxis()->SetTitle("obs/exp");
   ratioH__11->GetYaxis()->SetNdivisions(505);
   ratioH__11->GetYaxis()->SetLabelFont(42);
   ratioH__11->GetYaxis()->SetLabelOffset(0.01);
   ratioH__11->GetYaxis()->SetLabelSize(0.13);
   ratioH__11->GetYaxis()->SetTitleSize(0.14);
   ratioH__11->GetYaxis()->SetTickLength(0.04);
   ratioH__11->GetYaxis()->SetTitleOffset(0.5);
   ratioH__11->GetYaxis()->SetTitleFont(42);
   ratioH__11->GetZaxis()->SetLabelFont(42);
   ratioH__11->GetZaxis()->SetLabelOffset(0.007);
   ratioH__11->GetZaxis()->SetLabelSize(0.05);
   ratioH__11->GetZaxis()->SetTitleSize(0.06);
   ratioH__11->GetZaxis()->SetTitleFont(42);
   ratioH__11->Draw("e1");
   
   TH1F *ratioErrH__12 = new TH1F("ratioErrH__12","Observed",1,60,120);
   ratioErrH__12->SetBinContent(1,1);
   ratioErrH__12->SetBinContent(2,1);
   ratioErrH__12->SetBinError(1,0.1120711);
   ratioErrH__12->SetEntries(19);
   ratioErrH__12->SetOption("E1");
   ratioErrH__12->SetFillColor(1);
   ratioErrH__12->SetFillStyle(3013);
   ratioErrH__12->SetMarkerStyle(21);
   ratioErrH__12->SetMarkerSize(0);
   ratioErrH__12->GetXaxis()->SetTitle("m_{vis} [GeV]");
   ratioErrH__12->GetXaxis()->SetLabelFont(42);
   ratioErrH__12->GetXaxis()->SetLabelOffset(0.007);
   ratioErrH__12->GetXaxis()->SetLabelSize(0.05);
   ratioErrH__12->GetXaxis()->SetTitleSize(0.06);
   ratioErrH__12->GetXaxis()->SetTitleOffset(0.9);
   ratioErrH__12->GetXaxis()->SetTitleFont(42);
   ratioErrH__12->GetYaxis()->SetLabelFont(42);
   ratioErrH__12->GetYaxis()->SetLabelOffset(0.007);
   ratioErrH__12->GetYaxis()->SetLabelSize(0.05);
   ratioErrH__12->GetYaxis()->SetTitleSize(0.06);
   ratioErrH__12->GetYaxis()->SetTitleOffset(1.25);
   ratioErrH__12->GetYaxis()->SetTitleFont(42);
   ratioErrH__12->GetZaxis()->SetLabelFont(42);
   ratioErrH__12->GetZaxis()->SetLabelOffset(0.007);
   ratioErrH__12->GetZaxis()->SetLabelSize(0.05);
   ratioErrH__12->GetZaxis()->SetTitleSize(0.06);
   ratioErrH__12->GetZaxis()->SetTitleFont(42);
   ratioErrH__12->Draw("e2same");
   
   TH1F *ratioH_copy__13 = new TH1F("ratioH_copy__13","",1,60,120);
   ratioH_copy__13->SetBinContent(1,1.214454);
   ratioH_copy__13->SetBinContent(2,1000);
   ratioH_copy__13->SetBinError(1,0.00412075);
   ratioH_copy__13->SetMinimum(0.65);
   ratioH_copy__13->SetMaximum(1.35);
   ratioH_copy__13->SetEntries(13);
   ratioH_copy__13->SetDirectory(0);
   ratioH_copy__13->SetStats(0);
   ratioH_copy__13->SetOption("E1");
   ratioH_copy__13->SetFillStyle(0);
   ratioH_copy__13->SetLineWidth(2);
   ratioH_copy__13->SetMarkerStyle(20);
   ratioH_copy__13->SetMarkerSize(1.5);
   ratioH_copy__13->GetXaxis()->SetTitle("m_{vis} [GeV]");
   ratioH_copy__13->GetXaxis()->SetRange(1,1);
   ratioH_copy__13->GetXaxis()->SetLabelFont(42);
   ratioH_copy__13->GetXaxis()->SetLabelOffset(0.04);
   ratioH_copy__13->GetXaxis()->SetLabelSize(0.14);
   ratioH_copy__13->GetXaxis()->SetTitleSize(0.13);
   ratioH_copy__13->GetXaxis()->SetTickLength(0.07);
   ratioH_copy__13->GetXaxis()->SetTitleOffset(1.2);
   ratioH_copy__13->GetXaxis()->SetTitleFont(42);
   ratioH_copy__13->GetYaxis()->SetTitle("obs/exp");
   ratioH_copy__13->GetYaxis()->SetNdivisions(505);
   ratioH_copy__13->GetYaxis()->SetLabelFont(42);
   ratioH_copy__13->GetYaxis()->SetLabelOffset(0.01);
   ratioH_copy__13->GetYaxis()->SetLabelSize(0.13);
   ratioH_copy__13->GetYaxis()->SetTitleSize(0.14);
   ratioH_copy__13->GetYaxis()->SetTickLength(0.04);
   ratioH_copy__13->GetYaxis()->SetTitleOffset(0.5);
   ratioH_copy__13->GetYaxis()->SetTitleFont(42);
   ratioH_copy__13->GetZaxis()->SetLabelFont(42);
   ratioH_copy__13->GetZaxis()->SetLabelOffset(0.007);
   ratioH_copy__13->GetZaxis()->SetLabelSize(0.05);
   ratioH_copy__13->GetZaxis()->SetTitleSize(0.06);
   ratioH_copy__13->GetZaxis()->SetTitleFont(42);
   ratioH_copy__13->Draw("sameaxis");
   lower->Modified();
   canv1->cd();
   canv1->Modified();
   canv1->cd();
   canv1->SetSelected(canv1);
}
